/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sozn4xdvanckhn4w4dmtraajd4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v7mhj2pem5cmfi4t4v4563eogm",
    "aws_cognito_identity_pool_id": "us-east-1:1efd4ae1-5218-446d-b868-608c3b321781",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_M1Agr1Q6t",
    "aws_user_pools_web_client_id": "4e2o4povptqhrutpj01huvnqq2",
    "oauth": {},
    "aws_user_files_s3_bucket": "instatonypics151424-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
